### ISSUE TITLE
form关联关系数据不显示

### ISSUE THREAD

**Issue by joey2017** [jqhph/dcat-admin#419] opened 2020-08-11 07:11 UTC
- Laravel Version: 5.8
- PHP Version: 7.4
- Dcat Admin Version: 1.6

### Description:
            $form->image('auth.business_license', admin_trans_field('business_license'));
            $form->text('auth.credit_code', admin_trans_field('credit_code'))->required();
            $form->text('auth.register_address', admin_trans_field('register_address'))->required();
            $form->image('auth.front_image_url', admin_trans_field('front_image_url'));
            $form->image('auth.back_image_url', admin_trans_field('back_image_url'));
form一对一关联关系可以保存关联数据，但是编辑页面没显示关联的数据。
![image](https://user-images.githubusercontent.com/24761416/89868162-f1901700-dbe4-11ea-9df6-36f15f4fa97b.png)

而且，如果是把图片上传的字段设置成required，上传成功后会报其它字段不能为空的错误，比如我上传了business_license，马上会报front_image_url字段不能为空。虽然这个我可以通过去掉->required()进行修复，显然这个对页面来说，必填项会被认为可以不用上传，影响体验。

**Comment by jqhph** [comment] 2020-08-11 08:01
用法不对，参考文档 [表单关联关系](http://www.dcatadmin.com/docs/master/model-relationship.html)

**Comment by jqhph** [comment] 2020-08-11 08:01
Duplicate of #420

**Comment by joey2017** [comment] 2020-08-11 08:39
> 用法不对，参考文档 [表单关联关系](http://www.dcatadmin.com/docs/master/model-relationship.html)

不应该吧，我又对了一遍，一对一文档内容不多，这是我的form()方法代码：
return Form::make(Enterprise::with('auth'), function (Form $form) {
            $form->column(6, function (Form $form) {
                $form->display('enterprise_name')->required();
                $form->select('nature')
                    ->options(Constants::NATURES)
                    ->when(Constants::GAS, function (Form $form) {
                        $form->select('station_type')->options(Constants::STATION_TYPES)->required();
                    })->required();
                $form->mobile('mobile')->required();
                $form->text('bank_account')->required();
                $form->select('city_code')->options(function ($city_code) {
                    return [$city_code => City::getCityName($city_code)];
                })->ajax('enterprises/citys')->required();
                $form->text('tel');
                $form->text('summary');
                $form->email('email');
                $form->text('business_address', admin_trans_field('business_address'))->required();
                $form->image('auth.business_license', admin_trans_field('business_license'));
                $form->text('auth.credit_code', admin_trans_field('credit_code'))->required();
                $form->text('auth.register_address', admin_trans_field('register_address'))->required();
            });

            $form->column(6, function (Form $form) {
                $form->image('auth.front_image_url', admin_trans_field('front_image_url'));
                $form->image('auth.back_image_url', admin_trans_field('back_image_url'));
                $form->latlong('lat', 'lng', admin_trans_field('position'))->zoom(16);
                $form->switch('status')->default(1);
                $form->display('created_at')->default(date('Y-m-d H:i:s'));
                $form->display('updated_at')->default(date('Y-m-d H:i:s'));
            });
        });

模型一：
class Enterprise extends Model
{
    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function auth()
    {
        return $this->hasOne(EnterpriseAuthentication::class);
    }
}
模型二：
class EnterpriseAuthentication extends Model
{
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function enterprise()
    {
        return $this->belongsTo(Enterprise::class);
    }
}

**Comment by joey2017** [comment] 2020-08-11 08:43
> Duplicate of #420

突然可以了，我没改东西，不知道是什么原因，之前我已经强制刷新浏览器了

**Closed** 2020-12-23 02:05 UTC
Labels: question
